### ISSUE TITLE
Site broken

### ISSUE THREAD

**Issue by T8902** [vincevd1/thaliany#17]
![image](https://github.com/vincevd1/thaliany/assets/78494266/f102a7f0-6bfb-4c92-8d85-a940276f48e4)

![image](https://github.com/vincevd1/thaliany/assets/78494266/1bf8cded-80d3-4a6f-9056-00229dc0bdbb)

site breaks with 400s not sure what the case is since it doesn't happen for everyone.
![image](https://github.com/vincevd1/thaliany/assets/78494266/77d504e2-ca26-4112-9e2d-39d0eda52101)
![image](https://github.com/vincevd1/thaliany/assets/78494266/f53d06ed-f4e7-4afc-a0af-b8c5d06331e4)

It seems all anys are just broken for me. Not sure whether a request I did broke or something.

**Comment by vincevd1** [comment]
I'll download brave and check if I can recreate it somehow

**Comment by vincevd1** [comment]
Solved by #22
